[package]
name = "encode-practice"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
obj-rs = "0.7"
serde = "1"
bincode = "1"
serde_json = "1"
