[package]
name = "sqlx-practice"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.44.2", features = ["rt-multi-thread", "macros"] }
anyhow = "1"
