[package]
name = "opengl-practice"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
gl = "0.14"
glutin = "0.29"
