[package]
name = "dummy-ok-server"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
axum = "0.6"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
