[package]
name = "binlog-practice"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[dependencies]
mysql_cdc = "0.1"
walkdir = "2"
anyhow = { version = "1", features = ["backtrace"] }
clap = { version = "4.0.22", features = ["derive"] }
