on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libfontconfig-dev
          version: 0
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build
      - run: cargo test
      - run: cargo clippy --no-deps -- -D warnings
      - run: cargo fmt -- --check
